name: bedtime_stories
description: Flutter bedtime_stories app by Mayank Joshi
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_strategy: ^0.2.0
  responsive_builder: ^0.7.0
  flutter_animate: ^4.1.1+1
  flutter_secure_storage: ^9.0.0
  hive_flutter: ^1.1.0
  flutter_localization: ^0.1.13

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  generate: true
