name: bedtime_stories
description: Flutter bedtime_stories app by Mayank Joshi
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_localization: ^0.1.13
  flutter_secure_storage: ^9.0.0
  hive_flutter: ^1.1.0
  logger: ^1.1.0
  responsive_builder: ^0.7.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_strategy: ^0.2.0
  flutter_tts: ^3.8.3
  stacked_firebase_auth: ^2.19.4

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  generate: true
