// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVpREOSCVlYu3bCTDgpQocTbKMF9-0D9c',
    appId: '1:490202768187:web:799ef80730c79181180d1e',
    messagingSenderId: '490202768187',
    projectId: 'dreamy-tales',
    authDomain: 'dreamy-tales.firebaseapp.com',
    storageBucket: 'dreamy-tales.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuddpLokTW9iY7SXIwIEj-zRTIxmLaClY',
    appId: '1:490202768187:android:51146da7a81edb89180d1e',
    messagingSenderId: '490202768187',
    projectId: 'dreamy-tales',
    storageBucket: 'dreamy-tales.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrqQ97UgJZgX9S7XaRY9rNylAfqG7TyQw',
    appId: '1:490202768187:ios:92336e8e0eea4ed5180d1e',
    messagingSenderId: '490202768187',
    projectId: 'dreamy-tales',
    storageBucket: 'dreamy-tales.appspot.com',
    iosBundleId: 'com.mflutterapps.bedtimestories.bedtimeStories',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrqQ97UgJZgX9S7XaRY9rNylAfqG7TyQw',
    appId: '1:490202768187:ios:54aa73f800e29e51180d1e',
    messagingSenderId: '490202768187',
    projectId: 'dreamy-tales',
    storageBucket: 'dreamy-tales.appspot.com',
    iosBundleId: 'com.mflutterapps.bedtimestories.bedtimeStories.RunnerTests',
  );
}
