// Mocks generated by Mockito 5.4.2 from annotations
// in bedtime_stories/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i4;

import 'package:bedtime_stories/classes/story_request.dart' as _i19;
import 'package:bedtime_stories/classes/story_response.dart' as _i16;
import 'package:bedtime_stories/enums/signin_results.dart' as _i21;
import 'package:bedtime_stories/services/app_preferences_service.dart' as _i15;
import 'package:bedtime_stories/services/app_theme_service.dart' as _i17;
import 'package:bedtime_stories/services/http_service.dart' as _i18;
import 'package:bedtime_stories/services/tts_service.dart' as _i8;
import 'package:bedtime_stories/services/user_service.dart' as _i20;
import 'package:flutter/material.dart' as _i5;
import 'package:flutter_tts/flutter_tts.dart' as _i7;
import 'package:hive_flutter/hive_flutter.dart' as _i3;
import 'package:logger/src/logger.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:stacked/stacked.dart' as _i2;
import 'package:stacked_services/src/bottom_sheet/bottom_sheet_service.dart'
    as _i11;
import 'package:stacked_services/src/dialog/dialog_service.dart' as _i13;
import 'package:stacked_services/src/models/overlay_request.dart' as _i14;
import 'package:stacked_services/src/models/overlay_response.dart' as _i12;
import 'package:stacked_services/src/navigation/router_service.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRootStackRouter_0 extends _i1.SmartFake
    implements _i2.RootStackRouter {
  _FakeRootStackRouter_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRouteData_1 extends _i1.SmartFake implements _i2.RouteData {
  _FakeRouteData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRoutingController_2 extends _i1.SmartFake
    implements _i2.RoutingController {
  _FakeRoutingController_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBox_3<E> extends _i1.SmartFake implements _i3.Box<E> {
  _FakeBox_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocale_4 extends _i1.SmartFake implements _i4.Locale {
  _FakeLocale_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeThemeData_5 extends _i1.SmartFake implements _i5.ThemeData {
  _FakeThemeData_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeLogger_6 extends _i1.SmartFake implements _i6.Logger {
  _FakeLogger_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterTts_7 extends _i1.SmartFake implements _i7.FlutterTts {
  _FakeFlutterTts_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTtsPoint_8 extends _i1.SmartFake implements _i8.TtsPoint {
  _FakeTtsPoint_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RouterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouterService extends _i1.Mock implements _i9.RouterService {
  @override
  _i2.RootStackRouter get router => (super.noSuchMethod(
        Invocation.getter(#router),
        returnValue: _FakeRootStackRouter_0(
          this,
          Invocation.getter(#router),
        ),
        returnValueForMissingStub: _FakeRootStackRouter_0(
          this,
          Invocation.getter(#router),
        ),
      ) as _i2.RootStackRouter);
  @override
  set router(_i2.RootStackRouter? _router) => super.noSuchMethod(
        Invocation.setter(
          #router,
          _router,
        ),
        returnValueForMissingStub: null,
      );
  @override
  List<_i2.StackedPage<dynamic>> get stack => (super.noSuchMethod(
        Invocation.getter(#stack),
        returnValue: <_i2.StackedPage<dynamic>>[],
        returnValueForMissingStub: <_i2.StackedPage<dynamic>>[],
      ) as List<_i2.StackedPage<dynamic>>);
  @override
  _i2.RouteData get topRoute => (super.noSuchMethod(
        Invocation.getter(#topRoute),
        returnValue: _FakeRouteData_1(
          this,
          Invocation.getter(#topRoute),
        ),
        returnValueForMissingStub: _FakeRouteData_1(
          this,
          Invocation.getter(#topRoute),
        ),
      ) as _i2.RouteData);
  @override
  dynamic setRouter(_i2.RootStackRouter? router) => super.noSuchMethod(
        Invocation.method(
          #setRouter,
          [router],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i10.Future<dynamic> navigateTo(
    _i2.PageRouteInfo<dynamic>? route, {
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [route],
          {#onFailure: onFailure},
        ),
        returnValue: _i10.Future<dynamic>.value(),
        returnValueForMissingStub: _i10.Future<dynamic>.value(),
      ) as _i10.Future<dynamic>);
  @override
  _i10.Future<void> navigateToPath({
    required String? path,
    bool? includePrefixMatches = false,
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToPath,
          [],
          {
            #path: path,
            #includePrefixMatches: includePrefixMatches,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<T?> navigateWithTransition<T extends Object?>(
    _i5.Widget? widget, {
    _i5.RouteTransitionsBuilder? transitionBuilder,
    bool? fullscreenDialog = false,
    Duration? transitionDuration = const Duration(milliseconds: 300),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithTransition,
          [widget],
          {
            #transitionBuilder: transitionBuilder,
            #fullscreenDialog: fullscreenDialog,
            #transitionDuration: transitionDuration,
          },
        ),
        returnValue: _i10.Future<T?>.value(),
        returnValueForMissingStub: _i10.Future<T?>.value(),
      ) as _i10.Future<T?>);
  @override
  _i10.Future<T?> replaceWith<T extends Object?>(
    _i2.PageRouteInfo<dynamic>? route, {
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWith,
          [route],
          {#onFailure: onFailure},
        ),
        returnValue: _i10.Future<T?>.value(),
        returnValueForMissingStub: _i10.Future<T?>.value(),
      ) as _i10.Future<T?>);
  @override
  _i10.Future<void> clearStackAndShow(
    _i2.PageRouteInfo<dynamic>? route, {
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShow,
          [route],
          {#onFailure: onFailure},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> clearStackAndShowView(
    _i5.Widget? widget, {
    _i5.RouteTransitionsBuilder? transitionBuilder,
    bool? fullscreenDialog = false,
    Duration? transitionDuration = const Duration(milliseconds: 300),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShowView,
          [widget],
          {
            #transitionBuilder: transitionBuilder,
            #fullscreenDialog: fullscreenDialog,
            #transitionDuration: transitionDuration,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  void popForced<T extends Object?>([T? result]) => super.noSuchMethod(
        Invocation.method(
          #popForced,
          [result],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i10.Future<bool> pop<T extends Object?>([T? result]) => (super.noSuchMethod(
        Invocation.method(
          #pop,
          [result],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
  @override
  void back<T extends Object?>({T? result}) => super.noSuchMethod(
        Invocation.method(
          #back,
          [],
          {#result: result},
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i2.RoutingController topMostRouter({bool? ignorePagelessRoutes = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #topMostRouter,
          [],
          {#ignorePagelessRoutes: ignorePagelessRoutes},
        ),
        returnValue: _FakeRoutingController_2(
          this,
          Invocation.method(
            #topMostRouter,
            [],
            {#ignorePagelessRoutes: ignorePagelessRoutes},
          ),
        ),
        returnValueForMissingStub: _FakeRoutingController_2(
          this,
          Invocation.method(
            #topMostRouter,
            [],
            {#ignorePagelessRoutes: ignorePagelessRoutes},
          ),
        ),
      ) as _i2.RoutingController);
  @override
  _i10.Future<T?> pushNativeRoute<T extends Object?>(_i5.Route<T>? route) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNativeRoute,
          [route],
        ),
        returnValue: _i10.Future<T?>.value(),
        returnValueForMissingStub: _i10.Future<T?>.value(),
      ) as _i10.Future<T?>);
}

/// A class which mocks [BottomSheetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBottomSheetService extends _i1.Mock
    implements _i11.BottomSheetService {
  @override
  void setCustomSheetBuilders(Map<dynamic, _i11.SheetBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #setCustomSheetBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i10.Future<_i12.SheetResponse<dynamic>?> showBottomSheet({
    required String? title,
    String? description,
    String? confirmButtonTitle = r'Ok',
    String? cancelButtonTitle,
    bool? enableDrag = true,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBottomSheet,
          [],
          {
            #title: title,
            #description: description,
            #confirmButtonTitle: confirmButtonTitle,
            #cancelButtonTitle: cancelButtonTitle,
            #enableDrag: enableDrag,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i10.Future<_i12.SheetResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i10.Future<_i12.SheetResponse<dynamic>?>.value(),
      ) as _i10.Future<_i12.SheetResponse<dynamic>?>);
  @override
  _i10.Future<_i12.SheetResponse<T>?> showCustomSheet<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i4.Color? barrierColor = const _i4.Color(2315255808),
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    String? barrierLabel = r'',
    dynamic customData,
    R? data,
    bool? enableDrag = true,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomSheet,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #barrierLabel: barrierLabel,
            #customData: customData,
            #data: data,
            #enableDrag: enableDrag,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i10.Future<_i12.SheetResponse<T>?>.value(),
        returnValueForMissingStub: _i10.Future<_i12.SheetResponse<T>?>.value(),
      ) as _i10.Future<_i12.SheetResponse<T>?>);
  @override
  void completeSheet(_i12.SheetResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeSheet,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i13.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i13.DialogBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void registerCustomDialogBuilder({
    required dynamic variant,
    required _i5.Widget Function(
      _i5.BuildContext,
      _i14.DialogRequest<dynamic>,
      dynamic Function(_i12.DialogResponse<dynamic>),
    )? builder,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilder,
          [],
          {
            #variant: variant,
            #builder: builder,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i10.Future<_i12.DialogResponse<dynamic>?> showDialog({
    String? title,
    String? description,
    String? cancelTitle,
    _i4.Color? cancelTitleColor,
    String? buttonTitle = r'Ok',
    _i4.Color? buttonTitleColor,
    bool? barrierDismissible = false,
    _i13.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #buttonTitle: buttonTitle,
            #buttonTitleColor: buttonTitleColor,
            #barrierDismissible: barrierDismissible,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i10.Future<_i12.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i10.Future<_i12.DialogResponse<dynamic>?>.value(),
      ) as _i10.Future<_i12.DialogResponse<dynamic>?>);
  @override
  _i10.Future<_i12.DialogResponse<T>?> showCustomDialog<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i4.Color? barrierColor = const _i4.Color(2315255808),
    bool? barrierDismissible = false,
    String? barrierLabel = r'',
    bool? useSafeArea = true,
    dynamic customData,
    R? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomDialog,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #barrierLabel: barrierLabel,
            #useSafeArea: useSafeArea,
            #customData: customData,
            #data: data,
          },
        ),
        returnValue: _i10.Future<_i12.DialogResponse<T>?>.value(),
        returnValueForMissingStub: _i10.Future<_i12.DialogResponse<T>?>.value(),
      ) as _i10.Future<_i12.DialogResponse<T>?>);
  @override
  _i10.Future<_i12.DialogResponse<dynamic>?> showConfirmationDialog({
    String? title,
    String? description,
    String? cancelTitle = r'Cancel',
    _i4.Color? cancelTitleColor,
    String? confirmationTitle = r'Ok',
    _i4.Color? confirmationTitleColor,
    bool? barrierDismissible = false,
    _i13.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showConfirmationDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #confirmationTitle: confirmationTitle,
            #confirmationTitleColor: confirmationTitleColor,
            #barrierDismissible: barrierDismissible,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i10.Future<_i12.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i10.Future<_i12.DialogResponse<dynamic>?>.value(),
      ) as _i10.Future<_i12.DialogResponse<dynamic>?>);
  @override
  void completeDialog(_i12.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeDialog,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AppPreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppPreferencesService extends _i1.Mock
    implements _i15.AppPreferencesService {
  @override
  List<int> get key => (super.noSuchMethod(
        Invocation.getter(#key),
        returnValue: <int>[],
        returnValueForMissingStub: <int>[],
      ) as List<int>);
  @override
  set key(List<int>? _key) => super.noSuchMethod(
        Invocation.setter(
          #key,
          _key,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Box<dynamic> get appHelperBox => (super.noSuchMethod(
        Invocation.getter(#appHelperBox),
        returnValue: _FakeBox_3<dynamic>(
          this,
          Invocation.getter(#appHelperBox),
        ),
        returnValueForMissingStub: _FakeBox_3<dynamic>(
          this,
          Invocation.getter(#appHelperBox),
        ),
      ) as _i3.Box<dynamic>);
  @override
  set appHelperBox(_i3.Box<dynamic>? _appHelperBox) => super.noSuchMethod(
        Invocation.setter(
          #appHelperBox,
          _appHelperBox,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Locale getAppLanguageLocale() => (super.noSuchMethod(
        Invocation.method(
          #getAppLanguageLocale,
          [],
        ),
        returnValue: _FakeLocale_4(
          this,
          Invocation.method(
            #getAppLanguageLocale,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeLocale_4(
          this,
          Invocation.method(
            #getAppLanguageLocale,
            [],
          ),
        ),
      ) as _i4.Locale);
  @override
  void setAppLanguageLocale({required _i4.Locale? locale}) =>
      super.noSuchMethod(
        Invocation.method(
          #setAppLanguageLocale,
          [],
          {#locale: locale},
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i10.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  void saveStory({required _i16.StoryResponse? story}) => super.noSuchMethod(
        Invocation.method(
          #saveStory,
          [],
          {#story: story},
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AppThemeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppThemeService extends _i1.Mock implements _i17.AppThemeService {
  @override
  int get colorSelected => (super.noSuchMethod(
        Invocation.getter(#colorSelected),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  _i5.ThemeData get themeData => (super.noSuchMethod(
        Invocation.getter(#themeData),
        returnValue: _FakeThemeData_5(
          this,
          Invocation.getter(#themeData),
        ),
        returnValueForMissingStub: _FakeThemeData_5(
          this,
          Invocation.getter(#themeData),
        ),
      ) as _i5.ThemeData);
  @override
  _i4.Locale get appLocale => (super.noSuchMethod(
        Invocation.getter(#appLocale),
        returnValue: _FakeLocale_4(
          this,
          Invocation.getter(#appLocale),
        ),
        returnValueForMissingStub: _FakeLocale_4(
          this,
          Invocation.getter(#appLocale),
        ),
      ) as _i4.Locale);
  @override
  List<_i17.ThemeColorOptions> get colorOptions => (super.noSuchMethod(
        Invocation.getter(#colorOptions),
        returnValue: <_i17.ThemeColorOptions>[],
        returnValueForMissingStub: <_i17.ThemeColorOptions>[],
      ) as List<_i17.ThemeColorOptions>);
  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  _i5.ThemeData updateThemes(
    int? colorIndex,
    bool? useMaterial3,
    bool? useLightMode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateThemes,
          [
            colorIndex,
            useMaterial3,
            useLightMode,
          ],
        ),
        returnValue: _FakeThemeData_5(
          this,
          Invocation.method(
            #updateThemes,
            [
              colorIndex,
              useMaterial3,
              useLightMode,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeThemeData_5(
          this,
          Invocation.method(
            #updateThemes,
            [
              colorIndex,
              useMaterial3,
              useLightMode,
            ],
          ),
        ),
      ) as _i5.ThemeData);
  @override
  void handleBrightnessChange() => super.noSuchMethod(
        Invocation.method(
          #handleBrightnessChange,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void handleColorSelect(int? value) => super.noSuchMethod(
        Invocation.method(
          #handleColorSelect,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void handleDarkModeSelect(bool? value) => super.noSuchMethod(
        Invocation.method(
          #handleDarkModeSelect,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void handleMaterial3Select(bool? value) => super.noSuchMethod(
        Invocation.method(
          #handleMaterial3Select,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Locale getLocaleFromPref() => (super.noSuchMethod(
        Invocation.method(
          #getLocaleFromPref,
          [],
        ),
        returnValue: _FakeLocale_4(
          this,
          Invocation.method(
            #getLocaleFromPref,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeLocale_4(
          this,
          Invocation.method(
            #getLocaleFromPref,
            [],
          ),
        ),
      ) as _i4.Locale);
  @override
  void changeAppLocale({required _i4.Locale? appLocale}) => super.noSuchMethod(
        Invocation.method(
          #changeAppLocale,
          [],
          {#appLocale: appLocale},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [HttpService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpService extends _i1.Mock implements _i18.HttpService {
  @override
  _i6.Logger get log => (super.noSuchMethod(
        Invocation.getter(#log),
        returnValue: _FakeLogger_6(
          this,
          Invocation.getter(#log),
        ),
        returnValueForMissingStub: _FakeLogger_6(
          this,
          Invocation.getter(#log),
        ),
      ) as _i6.Logger);
  @override
  _i10.Future<_i16.StoryResponse?> getStoryResponse(
          {required _i19.StoryRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStoryResponse,
          [],
          {#request: request},
        ),
        returnValue: _i10.Future<_i16.StoryResponse?>.value(),
        returnValueForMissingStub: _i10.Future<_i16.StoryResponse?>.value(),
      ) as _i10.Future<_i16.StoryResponse?>);
}

/// A class which mocks [TtsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTtsService extends _i1.Mock implements _i8.TtsService {
  @override
  _i7.FlutterTts get flutterTts => (super.noSuchMethod(
        Invocation.getter(#flutterTts),
        returnValue: _FakeFlutterTts_7(
          this,
          Invocation.getter(#flutterTts),
        ),
        returnValueForMissingStub: _FakeFlutterTts_7(
          this,
          Invocation.getter(#flutterTts),
        ),
      ) as _i7.FlutterTts);
  @override
  set flutterTts(_i7.FlutterTts? _flutterTts) => super.noSuchMethod(
        Invocation.setter(
          #flutterTts,
          _flutterTts,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set language(String? _language) => super.noSuchMethod(
        Invocation.setter(
          #language,
          _language,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set engine(String? _engine) => super.noSuchMethod(
        Invocation.setter(
          #engine,
          _engine,
        ),
        returnValueForMissingStub: null,
      );
  @override
  double get volume => (super.noSuchMethod(
        Invocation.getter(#volume),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);
  @override
  set volume(double? _volume) => super.noSuchMethod(
        Invocation.setter(
          #volume,
          _volume,
        ),
        returnValueForMissingStub: null,
      );
  @override
  double get pitch => (super.noSuchMethod(
        Invocation.getter(#pitch),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);
  @override
  set pitch(double? _pitch) => super.noSuchMethod(
        Invocation.setter(
          #pitch,
          _pitch,
        ),
        returnValueForMissingStub: null,
      );
  @override
  double get rate => (super.noSuchMethod(
        Invocation.getter(#rate),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);
  @override
  set rate(double? _rate) => super.noSuchMethod(
        Invocation.setter(
          #rate,
          _rate,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get isCurrentLanguageInstalled => (super.noSuchMethod(
        Invocation.getter(#isCurrentLanguageInstalled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  set isCurrentLanguageInstalled(bool? _isCurrentLanguageInstalled) =>
      super.noSuchMethod(
        Invocation.setter(
          #isCurrentLanguageInstalled,
          _isCurrentLanguageInstalled,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i8.TtsState get currentState => (super.noSuchMethod(
        Invocation.getter(#currentState),
        returnValue: _i8.TtsState.playing,
        returnValueForMissingStub: _i8.TtsState.playing,
      ) as _i8.TtsState);
  @override
  _i8.TtsPoint get currentWord => (super.noSuchMethod(
        Invocation.getter(#currentWord),
        returnValue: _FakeTtsPoint_8(
          this,
          Invocation.getter(#currentWord),
        ),
        returnValueForMissingStub: _FakeTtsPoint_8(
          this,
          Invocation.getter(#currentWord),
        ),
      ) as _i8.TtsPoint);
  @override
  bool get isIOS => (super.noSuchMethod(
        Invocation.getter(#isIOS),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  bool get isAndroid => (super.noSuchMethod(
        Invocation.getter(#isAndroid),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  bool get isWindows => (super.noSuchMethod(
        Invocation.getter(#isWindows),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  bool get isWeb => (super.noSuchMethod(
        Invocation.getter(#isWeb),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  void setTtsState({required _i8.TtsState? state}) => super.noSuchMethod(
        Invocation.method(
          #setTtsState,
          [],
          {#state: state},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void speak() => super.noSuchMethod(
        Invocation.method(
          #speak,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void stop() => super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void pause() => super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setSpeakingText({required String? text}) => super.noSuchMethod(
        Invocation.method(
          #setSpeakingText,
          [],
          {#text: text},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i20.UserService {
  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  _i10.Future<_i21.SignInResult> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i10.Future<_i21.SignInResult>.value(
            _i21.SignInResult.createdAccount),
        returnValueForMissingStub: _i10.Future<_i21.SignInResult>.value(
            _i21.SignInResult.createdAccount),
      ) as _i10.Future<_i21.SignInResult>);
  @override
  _i10.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
